import type { Metadata } from 'next';
import { Baloo_2, Inter } from 'next/font/google';
import './globals.css';
import Navbar from './_custom_components/Navbar';
import { Toaster } from 'sonner';
import UserProvider from './_contexts/user/UserProvider';

const baloo = Baloo_2({
  subsets: ['latin'],
  variable: '--font-logo',
  weight: ['400', '500', '600', '700', '800'],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-accent',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'PegPal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative min-h-screen flex flex-col bg-[url('/white-snow.jpg')] bg-cover bg-fixed bg-center ${baloo.variable} ${inter.variable}`}
      >
        <UserProvider>
          <div
            className={`pt-5 px-6 lg:px-10 sticky top-0 z-50 bg-[url('/white-snow.jpg')] bg-cover bg-fixed bg-center`}
          >
            <Navbar />
          </div>
          <main className="flex-1 flex flex-col py-10 px-6 lg:p-10">
            {children}
          </main>
          <Toaster richColors />
        </UserProvider>
      </body>
    </html>
  );
}
