import type { Metadata } from 'next';
import { Baloo_2, Inter } from 'next/font/google';
import './globals.css';
import Navbar from './_custom_components/Navbar';
import { Toaster } from 'sonner';

const baloo = Baloo_2({
  subsets: ['latin'],
  variable: '--font-logo',
  weight: ['400', '500', '600', '700', '800'],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-accent',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'PegPal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative flex flex-col h-screen ${baloo.variable} ${inter.variable}`}
      >
        <Navbar />
        <main className="top-15 flex-1 min-h-0 overflow-auto space-y-8 md:space-y-0 md:space-x-12">
          {children}
        </main>
        <Toaster richColors />
      </body>
    </html>
  );
}
